#ifndef AILANG_RUNTIME_H
#define AILANG_RUNTIME_H

#include <stdbool.h>
#include <stdint.h>

int64_t ailang_rt_identity_i64(int64_t value);
bool ailang_rt_identity_bool(bool value);
int64_t ailang_rt_time_now(void);
void ailang_rt_log_any();
int64_t ailang_rt_log_event();
int64_t ailang_rt_log_field();
int64_t ailang_rt_log_obj();
int64_t ailang_rt_log_str();
int64_t ailang_rt_log_i64();
int64_t ailang_rt_log_bool();
int64_t ailang_rt_log_redacted();
int64_t ailang_rt_req_json();
int64_t ailang_rt_req_body();
int64_t ailang_rt_req_query();
int64_t ailang_rt_req_path_param();
int64_t ailang_rt_req_header();
int64_t ailang_rt_res_json();
int64_t ailang_rt_res_ok();
int64_t ailang_rt_res_ok_meta();
int64_t ailang_rt_res_html();
int64_t ailang_rt_set_header();
int64_t ailang_rt_set_cookie();
int64_t ailang_rt_db_exec();
int64_t ailang_rt_db_query_one();
int64_t ailang_rt_fs_read();
int64_t ailang_rt_fs_write();
int64_t ailang_rt_http_get();
int64_t ailang_rt_http_get_internal();
int64_t ailang_rt_secret_get();
int64_t ailang_rt_secret_redact();
int64_t ailang_rt_secret_reveal();
int64_t ailang_rt_validate_header_value();
int64_t ailang_rt_validate_email();
int64_t ailang_rt_validate_uuid();
int64_t ailang_rt_validate_int64();
int64_t ailang_rt_validate_non_empty();
int64_t ailang_rt_sanitize_html();
int64_t ailang_rt_url_public();
int64_t ailang_rt_url_internal();
int64_t ailang_rt_path_under();
int64_t ailang_rt_path_base();
int64_t ailang_rt_headers_name();
int64_t ailang_rt_headers_value();
int64_t ailang_rt_http_router();
int64_t ailang_rt_http_route_get();
int64_t ailang_rt_http_route_post();
int64_t ailang_rt_http_serve();
int64_t ailang_rt_with_cors();
int64_t ailang_rt_with_security_headers();
int64_t ailang_rt_with_csrf();
int64_t ailang_rt_with_auth();
int64_t ailang_rt_sec_default_headers();
int64_t ailang_rt_sec_csp();
int64_t ailang_rt_sec_csp_add();
int64_t ailang_rt_cors_from_policy();
int64_t ailang_rt_cors_origin();
int64_t ailang_rt_csrf_from_policy();
int64_t ailang_rt_csrf_issue_token();
int64_t ailang_rt_auth_from_policy();
int64_t ailang_rt_auth_require();
int64_t ailang_rt_auth_require_role();

#endif
