id = "untrusted"
name = "Untrusted<T>"
version = "0.1.0"
schema_version = 1

[grammars.untrusted]
repository = "https://github.com/HubDev-AI/untrusted-compiler"
rev = "e5ab04b3d433f87d57d090127d056fb78df5d38b"

[language_servers.sec4audit-lsp]
name = "Untrusted<T> Language Server"
languages = ["Untrusted<T>"]
