id = "untrusted"
name = "Untrusted<T>"
version = "0.1.0"
schema_version = 1

[grammars.untrusted]
repository = "https://github.com/HubDev-AI/untrusted-compiler"
rev = "TODO_SET_COMMIT_SHA"

[language_servers.sec4audit-lsp]
name = "Untrusted<T> Language Server"
languages = ["Untrusted<T>"]
