#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

dry_run="false"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      dry_run="true"
      shift
      ;;
    -h|--help)
      cat <<'USAGE'
usage: scripts/run-naming-lock-contract-suite.sh [--dry-run]

Runs the full naming-lock contract test suite in deterministic order.
USAGE
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

step=1
run_step() {
  local cmd="$1"
  printf "[%d/%d] %s\n" "${step}" "${TOTAL_STEPS}" "${cmd}"
  if [ "${dry_run}" != "true" ]; then
    "${cmd}"
  fi
  step=$((step + 1))
}

TOTAL_STEPS=178

run_step "scripts/test-check-no-local-path-leaks.sh"
run_step "scripts/test-check-sec4-explain-audit-coverage.sh"
run_step "scripts/test-replay-capture-contract.sh"
run_step "scripts/test-replay-capture-compat.sh"
run_step "scripts/test-replay-stub-registry-contract.sh"
run_step "scripts/test-replay-cli-json-contract.sh"
run_step "scripts/test-replay-cli-json-contract-guard.sh"
run_step "scripts/test-m16-runtime-http-coverage.sh"
run_step "scripts/test-m16-runtime-http-coverage-guard.sh"
run_step "scripts/test-smoke-sec4-run-hello-api-script-contract.sh"
run_step "scripts/test-smoke-sec4-run-hello-api-script-contract-guard.sh"
run_step "scripts/test-runtime-smoke-workflow-contract.sh"
run_step "scripts/test-runtime-smoke-workflow-contract-guard.sh"
run_step "scripts/test-check-runtime-smoke-artifacts.sh"
run_step "scripts/test-build-runtime-smoke-branch-index.sh"
run_step "scripts/test-check-runtime-smoke-bundle.sh"
run_step "scripts/test-check-m17-operator-handoff-readiness.sh"
run_step "scripts/test-run-m17-operator-bootstrap.sh"
run_step "scripts/test-print-m17-operator-troubleshooting-matrix.sh"
run_step "scripts/test-run-m17-operator-handoff-quickstart.sh"
run_step "scripts/test-run-m17-operator-handoff-ci-smoke.sh"
run_step "scripts/test-operator-handoff-workflow-contract.sh"
run_step "scripts/test-operator-handoff-workflow-contract-guard.sh"
run_step "scripts/test-inspect-m17-operator-handoff-artifacts.sh"
run_step "scripts/test-summarize-m17-operator-handoff-readiness.sh"
run_step "scripts/test-build-m17-operator-release-packet.sh"
run_step "scripts/test-check-m17-operator-handoff-playbook.sh"
run_step "scripts/test-run-m17-operator-clean-clone-rehearsal.sh"
run_step "scripts/test-generate-m18-kickoff-brief.sh"
run_step "scripts/test-build-m18-priority-matrix.sh"
run_step "scripts/test-select-m18-next-slice.sh"
run_step "scripts/test-m18-editor-contract-expansion.sh"
run_step "scripts/test-m18-release-publish-integrity.sh"
run_step "scripts/test-run-m18-runtime-track.sh"
run_step "scripts/test-build-m18-track-convergence-summary.sh"
run_step "scripts/test-build-m18-transition-handoff-packet.sh"
run_step "scripts/test-build-m18-closure-report.sh"
run_step "scripts/test-generate-m19-kickoff-brief.sh"
run_step "scripts/test-build-m19-priority-matrix.sh"
run_step "scripts/test-select-m19-next-slice.sh"
run_step "scripts/test-run-m19-runtime-hardening.sh"
run_step "scripts/test-build-m19-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m19-transition-handoff-packet.sh"
run_step "scripts/test-build-m19-closure-report.sh"
run_step "scripts/test-generate-m20-kickoff-brief.sh"
run_step "scripts/test-build-m20-priority-matrix.sh"
run_step "scripts/test-select-m20-next-slice.sh"
run_step "scripts/test-run-m20-runtime-hardening.sh"
run_step "scripts/test-build-m20-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m20-transition-handoff-packet.sh"
run_step "scripts/test-build-m20-closure-report.sh"
run_step "scripts/test-generate-m21-kickoff-brief.sh"
run_step "scripts/test-build-m21-priority-matrix.sh"
run_step "scripts/test-select-m21-next-slice.sh"
run_step "scripts/test-run-m21-runtime-hardening.sh"
run_step "scripts/test-build-m21-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m21-transition-handoff-packet.sh"
run_step "scripts/test-build-m21-closure-report.sh"
run_step "scripts/test-generate-m22-kickoff-brief.sh"
run_step "scripts/test-build-m22-priority-matrix.sh"
run_step "scripts/test-select-m22-next-slice.sh"
run_step "scripts/test-run-m22-runtime-hardening.sh"
run_step "scripts/test-build-m22-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m22-transition-handoff-packet.sh"
run_step "scripts/test-build-m22-closure-report.sh"
run_step "scripts/test-generate-m23-kickoff-brief.sh"
run_step "scripts/test-build-m23-priority-matrix.sh"
run_step "scripts/test-select-m23-next-slice.sh"
run_step "scripts/test-run-m23-runtime-hardening.sh"
run_step "scripts/test-build-m23-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m23-transition-handoff-packet.sh"
run_step "scripts/test-build-m23-closure-report.sh"
run_step "scripts/test-generate-m24-kickoff-brief.sh"
run_step "scripts/test-build-m24-priority-matrix.sh"
run_step "scripts/test-select-m24-next-slice.sh"
run_step "scripts/test-run-m24-runtime-hardening.sh"
run_step "scripts/test-build-m24-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m24-transition-handoff-packet.sh"
run_step "scripts/test-build-m24-closure-report.sh"
run_step "scripts/test-generate-m25-kickoff-brief.sh"
run_step "scripts/test-build-m25-priority-matrix.sh"
run_step "scripts/test-select-m25-next-slice.sh"
run_step "scripts/test-run-m25-runtime-hardening.sh"
run_step "scripts/test-build-m25-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m25-transition-handoff-packet.sh"
run_step "scripts/test-build-m25-closure-report.sh"
run_step "scripts/test-generate-m26-kickoff-brief.sh"
run_step "scripts/test-build-m26-priority-matrix.sh"
run_step "scripts/test-select-m26-next-slice.sh"
run_step "scripts/test-run-m26-runtime-hardening.sh"
run_step "scripts/test-build-m26-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m26-transition-handoff-packet.sh"
run_step "scripts/test-build-m26-closure-report.sh"
run_step "scripts/test-generate-m27-kickoff-brief.sh"
run_step "scripts/test-build-m27-priority-matrix.sh"
run_step "scripts/test-select-m27-next-slice.sh"
run_step "scripts/test-run-m27-runtime-hardening.sh"
run_step "scripts/test-build-m27-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m27-transition-handoff-packet.sh"
run_step "scripts/test-build-m27-closure-report.sh"
run_step "scripts/test-generate-m28-kickoff-brief.sh"
run_step "scripts/test-build-m28-priority-matrix.sh"
run_step "scripts/test-select-m28-next-slice.sh"
run_step "scripts/test-run-m28-runtime-hardening.sh"
run_step "scripts/test-build-m28-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m28-transition-handoff-packet.sh"
run_step "scripts/test-build-m28-closure-report.sh"
run_step "scripts/test-generate-m29-kickoff-brief.sh"
run_step "scripts/test-build-m29-priority-matrix.sh"
run_step "scripts/test-plan-m29-runtime-destub.sh"
run_step "scripts/test-run-m29-runtime-destub.sh"
run_step "scripts/test-build-m29-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m29-transition-handoff-packet.sh"
run_step "scripts/test-build-m29-closure-report.sh"
run_step "scripts/test-generate-m30-kickoff-brief.sh"
run_step "scripts/test-build-m30-priority-matrix.sh"
run_step "scripts/test-plan-m30-runtime-destub.sh"
run_step "scripts/test-run-m30-runtime-destub.sh"
run_step "scripts/test-build-m30-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m30-transition-handoff-packet.sh"
run_step "scripts/test-build-m30-closure-report.sh"
run_step "scripts/test-generate-m31-kickoff-brief.sh"
run_step "scripts/test-build-m31-priority-matrix.sh"
run_step "scripts/test-plan-m31-runtime-destub.sh"
run_step "scripts/test-run-m31-runtime-destub.sh"
run_step "scripts/test-build-m31-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m31-transition-handoff-packet.sh"
run_step "scripts/test-build-m31-closure-report.sh"
run_step "scripts/test-generate-m32-kickoff-brief.sh"
run_step "scripts/test-build-m32-priority-matrix.sh"
run_step "scripts/test-plan-m32-runtime-destub.sh"
run_step "scripts/test-run-m32-runtime-destub.sh"
run_step "scripts/test-build-m32-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m32-transition-handoff-packet.sh"
run_step "scripts/test-build-m32-closure-report.sh"
run_step "scripts/test-generate-m33-kickoff-brief.sh"
run_step "scripts/test-build-m33-priority-matrix.sh"
run_step "scripts/test-plan-m33-runtime-destub.sh"
run_step "scripts/test-run-m33-runtime-destub.sh"
run_step "scripts/test-build-m33-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m33-transition-handoff-packet.sh"
run_step "scripts/test-build-m33-closure-report.sh"
run_step "scripts/test-generate-m34-kickoff-brief.sh"
run_step "scripts/test-build-m34-priority-matrix.sh"
run_step "scripts/test-plan-m34-runtime-destub.sh"
run_step "scripts/test-run-m34-runtime-destub.sh"
run_step "scripts/test-build-m34-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m34-transition-handoff-packet.sh"
run_step "scripts/test-build-m34-closure-report.sh"
run_step "scripts/test-generate-m35-kickoff-brief.sh"
run_step "scripts/test-build-m35-priority-matrix.sh"
run_step "scripts/test-plan-m35-runtime-destub.sh"
run_step "scripts/test-run-m35-runtime-destub.sh"
run_step "scripts/test-build-m35-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m35-transition-handoff-packet.sh"
run_step "scripts/test-build-m35-closure-report.sh"
run_step "scripts/test-build-m36-kickoff-brief.sh"
run_step "scripts/test-build-m36-priority-matrix.sh"
run_step "scripts/test-plan-m36-runtime-destub.sh"
run_step "scripts/test-run-m36-runtime-destub.sh"
run_step "scripts/test-build-m36-executed-slice-convergence-summary.sh"
run_step "scripts/test-build-m36-transition-handoff-packet.sh"
run_step "scripts/test-build-m36-closure-report.sh"
run_step "scripts/test-alpha-release-workflow-contract.sh"
run_step "scripts/test-alpha-release-workflow-contract-guard.sh"
run_step "scripts/test-roadmap-closure-gate-alignment.sh"
run_step "scripts/test-benchmark-cross-impl-workflow-contract.sh"
run_step "scripts/test-benchmark-cross-impl-workflow-contract-guard.sh"
run_step "scripts/test-benchmark-trend-workflow-contract.sh"
run_step "scripts/test-benchmark-trend-workflow-contract-guard.sh"
run_step "scripts/test-sec4-cli-command-contract.sh"
run_step "scripts/test-sec4-cli-command-contract-guard.sh"
run_step "scripts/test-sec4-run-runtime-flag-contract.sh"
run_step "scripts/test-sec4-run-runtime-flag-contract-guard.sh"
run_step "scripts/test-zed-grammar-pin.sh"
run_step "scripts/test-zed-grammar-pin-guard.sh"
run_step "scripts/test-release-contract-smoke-workflow-contract.sh"
run_step "scripts/test-release-contract-smoke-workflow-contract-guard.sh"
